export const azLang = {
    navBtns : ['Əsas Səhifə', 'Qiymətlər', 'Təqdimatlar','Son Hazırlananlar','Haqqımızda','Bizimlə Əlaqə'],
    headerTextContainer : ' komandası olaraq hər zaman daha yaxşısını etməyə hazırıq.',
    onlineOrderBtn : 'Online Sifariş ',
    sectionPricesHeader: 'Qiymətlər',
    presentationForLesson: 'Dərs üçün hazırlanmış təqdimatlar',
    presentationForWork: 'İş üçün hazırlanmış təqdimatlar',
    presentationForDiploma: 'Diplom işi üçün hazırlanmış təqdimatlar',
    priceOnePage: 'Bir səhifənin qiyməti',
    showBtn: 'Bax',
    section1Header : 'Hazırladığımız təqdimat nümunələri',
    section2Header : 'Son hazırladığımız təqdimatlar',
    section3Header : 'Haqqımızda',
    aboutTextContainer : 'Z-Presentation komandası olaraq 5 ildən artıq təcrübəmiz və minlərlə hazırladığımız təqdimatlar var. Bu illər ərzində bir çox fəndən sərbəst işləri Power Point - də hazırlamış və eyni zamanda diplom və dissertasiya müdafiələri üçün təqdimatlar hazırlamışıq. Bunlardan əlavə olaraq bir çox təşkilatların öz işləri haqqında olan informasiya xarakterli təqdimatlarımız da var. Sizdə işlərinizin hamı tərəfindən bəyənilməsini, digərlərindən fərqli və yadda qalan olmasını istəyirsinizsə işlərinizi bizə hazırladın.',
    section4Header : 'Bizimlə Əlaqə',
    onlineOrderHeader : 'ONLINE SIFARIŞ',
    topicLabel : 'Təqdimatın mövzusu',
    topicPlaceHolder : 'Mövzunu daxil edin',
    pageCountlabel : 'Səhifənin sayı',
    pageCountPlaceHolder : 'Sayı daxil edin',
    contactLabel : 'Əlaqə üçün WhatsApp nömrəsi',
    sendButton: 'Göndər',
    orderEmptyMsg: 'Zəhmət olmasa bütün xanaları doldurun',
    orderSuccessMsg: 'Sifarişiniz qeydə alındı. Sizinlə əlaqə saxlanılacaq',
    orderErrorMsg: 'Xəta baş verdi. Zəhmət olmasa yenidən cəhd edin'
}

export const engLang = {
    navBtns : ['Home Page','Prices', 'Presentations','Last Prepared','About Us','Contact Us'],
    headerTextContainer : ' teams are always ready to do their best.',
    onlineOrderBtn : 'Online Order ',
    sectionPricesHeader: 'Prices',
    presentationForLesson: 'Presentations prepared for the lesson',
    presentationForWork: 'Presentations prepared for work',
    presentationForDiploma: 'Presentations for the diplomas',
    priceOnePage: 'Price per page',
    showBtn: 'Show',
    section1Header : 'Examples of presentations we have prepared',
    section2Header : 'Recent presentations',
    section3Header : 'About Us',
    aboutTextContainer : 'As a Z-Presentation team, we have more than 5 years of experience and thousands of presentations. Over the years, we have prepared independent work on many subjects in Power Point, and at the same time prepared presentations for diploma and dissertation defense. In addition, we have informational presentations about the work of many organizations. If you want your work to be liked by everyone, to be different and memorable, prepare your work for us.',
    section4Header : 'Contact Us',
    onlineOrderHeader : 'ONLINE ORDER',
    topicLabel : 'The subject of the presentation',
    topicPlaceHolder : 'Enter a subject',
    pageCountlabel : 'Number of pages',
    pageCountPlaceHolder : 'Enter the number of pages',
    contactLabel : 'WhatsApp number for contact',
    sendButton: 'Send',
    orderEmptyMsg: 'Please fill in all fields',
    orderSuccessMsg: 'Your order has been registered. You will be contacted',
    orderErrorMsg: 'An error occurred. Please try again'
}